### ISSUE TITLE
code not working

### ISSUE THREAD

**Issue by bockor** [rubenwylleman/RSA-example#2]
tested your code on https://www.onlinegdb.com/online_python_compiler# earlier this morning.
It does not invite the user to input p,q,m

**Comment by rubenwylleman** [comment]
Misunderstood the assignment. thought the code should only run when imported and called on the main function.

if __name__ == "__main__":
    main()

is now added and should resolve this issue.

**Comment by bockor** [comment]
always test your code profoundly before submitting.
Pay also attention to the function naming convention

**Comment by bockor** [comment]
https://github.com/rubenwylleman/RSA-example/issues/2#issuecomment-429733870

Op ma 15 okt. 2018 om 09:02 schreef rubenwylleman <notifications@github.com
